//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductUP.Componets
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostProd
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int PostId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Product Product { get; set; }
    }
}
